name: Install and test goliothctl

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup goliothctl
        uses: goliothlabs/setup-goliothctl@main
        with:
          apiKey: ${{ secrets.APIKEY }}
          projectId: ${{ vars.PROJECTID }}

      - name: Create Device
        uses: goliothlabs/create-device@main
        with:
          deviceName: foobarbaz
          deviceTag: ci

      - name: Download file for Artifact
        id: dl-artifact
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'golioth/thingy91-golioth'
          file: 'app_update_thingy91_v1.0.0.bin'

      - name: Create Artifact
        uses: goliothlabs/create-artifact@main
        with:
          file: ~/app_update_thingy91_v1.0.0.bin
          version: 1.0.0

      - name: List devices
        run: goliothctl device list