name: Install and test goliothctl

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup goliothctl
        uses: goliothlabs/setup-goliothctl@main