name: Install and test goliothctl

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup goliothctl
        uses: goliothlabs/setup-goliothctl@main
        with:
          apiKey: ${{ secrets.APIKEY }}
          projectId: ${{ vars.PROJECTID }}

      - name: Create Device
        uses: beriberikix/create-resources@main
        with:
          deviceName: foobarbaz

      - name: List devices
        run: goliothctl device list